// Security-rules tests. Run with:  npm run test:rules
// Uses a throwaway "demo-" project in the local emulator; nothing here can
// reach the real Firebase project.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { initializeTestEnvironment, assertFails, assertSucceeds } from "@firebase/rules-unit-testing";
import { ref, uploadString, getBytes, deleteObject } from "firebase/storage";
import { query, where } from "firebase/firestore";
import { doc, getDoc, getDocs, collection, setDoc, updateDoc, deleteDoc, writeBatch, increment, serverTimestamp, addDoc } from "firebase/firestore";

const here = dirname(fileURLToPath(import.meta.url));
const env = await initializeTestEnvironment({ projectId: "demo-pf-management", storage: { rules: readFileSync(join(here, "storage.rules"), "utf8"), host: "127.0.0.1", port: 9299 }, firestore: { rules: readFileSync(join(dirname(fileURLToPath(import.meta.url)), "firestore.rules"), "utf8"), host: "127.0.0.1", port: 8787 } });
const sha = (s) => createHash("sha256").update(s).digest("hex");
let pass = 0, fail = 0;
const t = async (name, p) => { try { await p; pass++; console.log("  ok   ", name); } catch (e) { fail++; console.log("  FAIL ", name, "-", e.message.split("\n")[0]); } };

const seed = async () => {
  await env.clearFirestore();
  await env.withSecurityRulesDisabled(async (ctx) => {
    const db = ctx.firestore();
    await setDoc(doc(db, "users/admin1"), { role: "admin" });
    await setDoc(doc(db, "users/listener1"), { role: "user" });
    const base = { title: "Dinner", date: "2030-01-01", allowCancellation: true, positions: [{ id: "pA", name: "A", description: "", spotsNeeded: 1 }, { id: "pB", name: "B", description: "", spotsNeeded: 2 }], spotsByPosition: { pA: 1, pB: 2 }, filledCounts: {} };
    await setDoc(doc(db, "volunteerSignups/s1"), { ...base, status: "open" });
    await setDoc(doc(db, "volunteerSignups/draft1"), { ...base, status: "draft" });
    await setDoc(doc(db, "volunteerSignups/closed1"), { ...base, status: "closed" });
    await setDoc(doc(db, "volunteerSignups/nocancel"), { ...base, status: "open", allowCancellation: false, filledCounts: { pB: 1 } });
    await setDoc(doc(db, `volunteerSignups/nocancel/volunteers/${sha("k1")}`), { positionId: "pB", name: "N", email: "", phone: "", source: "self" });
    await setDoc(doc(db, "volunteerSignups/s1/volunteers/leaderAdded"), { positionId: "pB", name: "L", email: "l@x.com", phone: "", addedBy: "admin1" });
    await setDoc(doc(db, "volunteerSignups/s1/roster/leaderAdded"), { positionId: "pB", name: "L" });
    await setDoc(doc(db, "volunteerSignups/draft1/roster/d1"), { positionId: "pA", name: "Hidden" });
    await setDoc(doc(db, `volunteerSignups/nocancel/roster/${sha("k1")}`), { positionId: "pB", name: "N" });
    await updateDoc(doc(db, "volunteerSignups/s1"), { "filledCounts.pB": 1 });
    await setDoc(doc(db, "leaderForms/openform"), { title: "F", status: "open", fields: [] });
    await setDoc(doc(db, "leaderForms/closedform"), { title: "F", status: "closed", fields: [] });
    await setDoc(doc(db, "leaderPeople/p1"), { name: "X" });
    await setDoc(doc(db, "leaders/leader2"), { name: "Lee", email: "lee@x.com", role: "leader" });
    await setDoc(doc(db, "leaders/leader3"), { name: "Kim", email: "kim@x.com", role: "leader" });
    await setDoc(doc(db, "leaderAnnouncements/byLee"), { title: "T", body: "B", createdBy: "leader2", createdByName: "Lee" });
    await setDoc(doc(db, "leaderAnnouncements/byLee/comments/kimsComment"), { body: "Nice", createdBy: "leader3", createdByName: "Kim" });
    await setDoc(doc(db, "leaderAnnouncements/byLee/comments/adminsComment"), { body: "Ok", createdBy: "admin1", createdByName: "Admin" });
    await setDoc(doc(db, "leaders/leader4"), { name: "Pat", email: "pat@x.com", role: "leader" });
  });
};

const pub = () => env.unauthenticatedContext().firestore();
const admin = () => env.authenticatedContext("admin1").firestore();
const listener = () => env.authenticatedContext("listener1").firestore();
const vol = (over = {}) => ({ positionId: "pA", name: "Jane", email: "", phone: "", source: "self", createdAt: serverTimestamp(), ...over });
const signup = (db, sid, secret, pid = "pA", volOver = {}, sigOver = null, roster = undefined) => {
  const vid = sha(secret); const b = writeBatch(db);
  b.set(doc(db, `volunteerSignups/${sid}/volunteers/${vid}`), vol({ positionId: pid, ...volOver }));
  if (roster !== null) b.set(doc(db, `volunteerSignups/${sid}/roster/${vid}`), roster || { positionId: pid, name: volOver.name ?? "Jane", createdAt: serverTimestamp() });
  b.update(doc(db, `volunteerSignups/${sid}`), sigOver || { [`filledCounts.${pid}`]: increment(1), lastVolunteerId: vid });
  return b.commit();
};
const cancel = (db, sid, vid, secret, pid = "pA", withRoster = true) => { const b = writeBatch(db); b.delete(doc(db, `volunteerSignups/${sid}/volunteers/${vid}`)); if (withRoster) b.delete(doc(db, `volunteerSignups/${sid}/roster/${vid}`)); b.update(doc(db, `volunteerSignups/${sid}`), { [`filledCounts.${pid}`]: increment(-1), lastVolunteerId: vid, cancelProof: secret }); return b.commit(); };

console.log("READS"); await seed();
await t("public can load an open signup", assertSucceeds(getDoc(doc(pub(), "volunteerSignups/s1"))));
await t("public cannot load a draft", assertFails(getDoc(doc(pub(), "volunteerSignups/draft1"))));
await t("public cannot list signups", assertFails(getDocs(collection(pub(), "volunteerSignups"))));
await t("public cannot read volunteers", assertFails(getDocs(collection(pub(), "volunteerSignups/s1/volunteers"))));
await t("public cannot read one volunteer", assertFails(getDoc(doc(pub(), "volunteerSignups/s1/volunteers/leaderAdded"))));
await t("audio-app listener cannot read volunteers", assertFails(getDocs(collection(listener(), "volunteerSignups/s1/volunteers"))));
await t("leader can read volunteers", assertSucceeds(getDocs(collection(admin(), "volunteerSignups/s1/volunteers"))));

console.log("SELF-SIGNUP"); await seed();
await t("public can sign up for an open spot", assertSucceeds(signup(pub(), "s1", "secret1")));
await t("  ...count went to 1", (async () => { let c; await env.withSecurityRulesDisabled(async (x) => { c = (await getDoc(doc(x.firestore(), "volunteerSignups/s1"))).data().filledCounts.pA; }); if (c !== 1) throw new Error("count " + c); })());
await t("cannot take a full position", assertFails(signup(pub(), "s1", "secret2")));
await t("can take the other position", assertSucceeds(signup(pub(), "s1", "secret3", "pB")));
await t("cannot overfill pB (2 of 2)", assertFails(signup(pub(), "s1", "secret4", "pB")));
await seed();
await t("cannot bump the count by 2", assertFails(signup(pub(), "s1", "x1", "pB", {}, { "filledCounts.pB": increment(2), lastVolunteerId: sha("x1") })));
await t("cannot bump a different position than signed up for", assertFails(signup(pub(), "s1", "x2", "pA", {}, { "filledCounts.pB": increment(1), lastVolunteerId: sha("x2") })));
await t("cannot sign up for a made-up position", assertFails(signup(pub(), "s1", "x3", "pZ")));
await t("cannot add a volunteer without bumping the count", assertFails(setDoc(doc(pub(), `volunteerSignups/s1/volunteers/${sha("x4")}`), vol())));
await t("cannot bump the count without adding a volunteer", assertFails(updateDoc(doc(pub(), "volunteerSignups/s1"), { "filledCounts.pA": increment(1), lastVolunteerId: "ghost" })));
await t("cannot change the title while signing up", assertFails(signup(pub(), "s1", "x5", "pA", {}, { "filledCounts.pA": increment(1), lastVolunteerId: sha("x5"), title: "hacked" })));
await t("cannot raise capacity while signing up", assertFails(signup(pub(), "s1", "x6", "pA", {}, { "filledCounts.pA": increment(1), lastVolunteerId: sha("x6"), "spotsByPosition.pA": 99 })));
await t("cannot edit the signup directly", assertFails(updateDoc(doc(pub(), "volunteerSignups/s1"), { title: "hacked" })));
await t("cannot reopen a closed signup", assertFails(updateDoc(doc(pub(), "volunteerSignups/closed1"), { status: "open" })));
await t("cannot add extra fields to the volunteer", assertFails(signup(pub(), "s1", "x7", "pA", { addedBy: "admin1" })));
await t("cannot pose as leader-added (source != self)", assertFails(signup(pub(), "s1", "x8", "pA", { source: "leader" })));
await t("cannot submit an empty name", assertFails(signup(pub(), "s1", "x9", "pA", { name: "" })));
await t("cannot submit a huge name", assertFails(signup(pub(), "s1", "x10", "pA", { name: "a".repeat(101) })));
await t("cannot sign up on a closed signup", assertFails(signup(pub(), "closed1", "x11")));
await t("cannot sign up on a draft", assertFails(signup(pub(), "draft1", "x12")));
await t("cannot overwrite an existing volunteer doc", assertFails((() => { const db = pub(); const b = writeBatch(db); b.set(doc(db, "volunteerSignups/s1/volunteers/leaderAdded"), vol({ positionId: "pB" })); b.update(doc(db, "volunteerSignups/s1"), { "filledCounts.pB": increment(1), lastVolunteerId: "leaderAdded" }); return b.commit(); })()));
await t("public cannot delete a signup", assertFails(deleteDoc(doc(pub(), "volunteerSignups/s1"))));
await t("public cannot create a signup", assertFails(setDoc(doc(pub(), "volunteerSignups/new1"), { status: "open" })));

console.log("SELF-CANCEL"); await seed();
await signup(pub(), "s1", "mysecret");
const myId = sha("mysecret");
await t("cannot cancel with the wrong secret", assertFails(cancel(pub(), "s1", myId, "wrong")));
await t("cannot cancel knowing only the doc ID", assertFails(cancel(pub(), "s1", myId, myId)));
await t("cannot delete the volunteer doc alone", assertFails(deleteDoc(doc(pub(), `volunteerSignups/s1/volunteers/${myId}`))));
await t("cannot drop the count alone", assertFails(updateDoc(doc(pub(), "volunteerSignups/s1"), { "filledCounts.pA": increment(-1), lastVolunteerId: myId, cancelProof: "mysecret" })));
await t("cannot cancel a leader-added volunteer", assertFails(cancel(pub(), "s1", "leaderAdded", "anything", "pB")));
await t("cannot cancel when cancelling is turned off", assertFails(cancel(pub(), "nocancel", sha("k1"), "k1", "pB")));
await t("can cancel with the right secret", assertSucceeds(cancel(pub(), "s1", myId, "mysecret")));
await t("  ...count back to 0 and doc gone", (async () => { let c, e; await env.withSecurityRulesDisabled(async (x) => { c = (await getDoc(doc(x.firestore(), "volunteerSignups/s1"))).data().filledCounts.pA; e = (await getDoc(doc(x.firestore(), `volunteerSignups/s1/volunteers/${myId}`))).exists(); }); if (c !== 0 || e) throw new Error(`count ${c} exists ${e}`); })());
await t("can sign up again after cancelling", assertSucceeds(signup(pub(), "s1", "again")));

console.log("ROSTER"); await seed();
await t("public can read the roster of an open signup", assertSucceeds(getDocs(collection(pub(), "volunteerSignups/s1/roster"))));
await t("public can read the roster of a closed signup", assertSucceeds(getDocs(collection(pub(), "volunteerSignups/closed1/roster"))));
await t("public cannot read a draft's roster", assertFails(getDocs(collection(pub(), "volunteerSignups/draft1/roster"))));
await t("public STILL cannot read contact details", assertFails(getDoc(doc(pub(), "volunteerSignups/s1/volunteers/leaderAdded"))));
await t("signup without a roster entry is refused", assertFails(signup(pub(), "s1", "r1", "pA", {}, null, null)));
await t("roster name must match the volunteer's name", assertFails(signup(pub(), "s1", "r2", "pA", {}, null, { positionId: "pA", name: "Someone Else", createdAt: serverTimestamp() })));
await t("roster position must match", assertFails(signup(pub(), "s1", "r3", "pA", {}, null, { positionId: "pB", name: "Jane", createdAt: serverTimestamp() })));
await t("roster entry cannot carry extra fields", assertFails(signup(pub(), "s1", "r4", "pA", {}, null, { positionId: "pA", name: "Jane", createdAt: serverTimestamp(), email: "x@y.z" })));
await t("cannot add a roster name on its own", assertFails(setDoc(doc(pub(), "volunteerSignups/s1/roster/fake"), { positionId: "pA", name: "Fake", createdAt: serverTimestamp() })));
await t("cannot rename someone on the roster", assertFails(updateDoc(doc(pub(), "volunteerSignups/s1/roster/leaderAdded"), { name: "Changed" })));
await t("cannot delete a roster entry on its own", assertFails(deleteDoc(doc(pub(), "volunteerSignups/s1/roster/leaderAdded"))));
await t("valid signup writes volunteer + roster", assertSucceeds(signup(pub(), "s1", "r5")));
await t("cancel that leaves the roster name behind is refused", assertFails(cancel(pub(), "s1", sha("r5"), "r5", "pA", false)));
await t("cancel removes volunteer + roster", assertSucceeds(cancel(pub(), "s1", sha("r5"), "r5")));
await t("  ...roster entry gone", (async () => { let e; await env.withSecurityRulesDisabled(async (x) => { e = (await getDoc(doc(x.firestore(), `volunteerSignups/s1/roster/${sha("r5")}`))).exists(); }); if (e) throw new Error("still there"); })());
await t("leader can write the roster", assertSucceeds(setDoc(doc(admin(), "volunteerSignups/s1/roster/v77"), { positionId: "pA", name: "Z", createdAt: serverTimestamp() })));
await t("audio-app listener cannot write the roster", assertFails(setDoc(doc(listener(), "volunteerSignups/s1/roster/v78"), { positionId: "pA", name: "Z", createdAt: serverTimestamp() })));

console.log("LEADERS"); await seed();
await t("leader can add a volunteer", assertSucceeds((() => { const db = admin(); const b = writeBatch(db); b.set(doc(db, "volunteerSignups/s1/volunteers/v9"), { positionId: "pA", name: "Z", email: "", phone: "", addedBy: "admin1", createdAt: serverTimestamp() }); b.update(doc(db, "volunteerSignups/s1"), { "filledCounts.pA": increment(1) }); return b.commit(); })()));
await t("leader can edit a signup", assertSucceeds(updateDoc(doc(admin(), "volunteerSignups/s1"), { title: "New" })));
await t("leader can remove any volunteer", assertSucceeds(deleteDoc(doc(admin(), "volunteerSignups/s1/volunteers/leaderAdded"))));
await t("leader can read a draft", assertSucceeds(getDoc(doc(admin(), "volunteerSignups/draft1"))));
await t("audio-app listener cannot edit a signup", assertFails(updateDoc(doc(listener(), "volunteerSignups/s1"), { title: "x" })));
await t("audio-app listener cannot read people", assertFails(getDocs(collection(listener(), "leaderPeople"))));

console.log("FORMS + PEOPLE"); await seed();
await t("public can load a form", assertSucceeds(getDoc(doc(pub(), "leaderForms/openform"))));
await t("public cannot list forms", assertFails(getDocs(collection(pub(), "leaderForms"))));
await t("public can submit to an open form", assertSucceeds(addDoc(collection(pub(), "leaderForms/openform/submissions"), { answers: { a: "b" }, submittedAt: serverTimestamp() })));
await t("public cannot submit to a closed form", assertFails(addDoc(collection(pub(), "leaderForms/closedform/submissions"), { answers: {}, submittedAt: serverTimestamp() })));
await t("public cannot read submissions", assertFails(getDocs(collection(pub(), "leaderForms/openform/submissions"))));
await t("public cannot read people", assertFails(getDocs(collection(pub(), "leaderPeople"))));
await t("leader can read submissions", assertSucceeds(getDocs(collection(admin(), "leaderForms/openform/submissions"))));
await t("leader can add a person", assertSucceeds(addDoc(collection(admin(), "leaderPeople"), { name: "Y" })));

console.log("ANNOUNCEMENTS"); await seed();
const lee = () => env.authenticatedContext("leader2").firestore();
const kim = () => env.authenticatedContext("leader3").firestore();
const ann = (over = {}) => ({ title: "Hi", body: "There", createdBy: "leader3", createdByName: "Kim", createdAt: serverTimestamp(), ...over });
await t("leader can read announcements", assertSucceeds(getDocs(collection(kim(), "leaderAnnouncements"))));
await t("public cannot read announcements", assertFails(getDocs(collection(pub(), "leaderAnnouncements"))));
await t("audio-app listener cannot read announcements", assertFails(getDocs(collection(listener(), "leaderAnnouncements"))));
await t("leader can post under their own account", assertSucceeds(addDoc(collection(kim(), "leaderAnnouncements"), ann())));
await t("leader cannot post as someone else", assertFails(addDoc(collection(kim(), "leaderAnnouncements"), ann({ createdBy: "leader2" }))));
await t("listener cannot post", assertFails(addDoc(collection(listener(), "leaderAnnouncements"), ann({ createdBy: "listener1" }))));
await t("author can edit their own", assertSucceeds(updateDoc(doc(lee(), "leaderAnnouncements/byLee"), { title: "New", edited: true })));
await t("author cannot change the author name", assertFails(updateDoc(doc(lee(), "leaderAnnouncements/byLee"), { createdByName: "Someone Else" })));
await t("another leader cannot edit it", assertFails(updateDoc(doc(kim(), "leaderAnnouncements/byLee"), { title: "Hacked" })));
await t("another leader cannot delete it", assertFails(deleteDoc(doc(kim(), "leaderAnnouncements/byLee"))));
await t("main admin can edit anyone's", assertSucceeds(updateDoc(doc(admin(), "leaderAnnouncements/byLee"), { title: "Fixed" })));
await t("main admin can delete anyone's", assertSucceeds(deleteDoc(doc(admin(), "leaderAnnouncements/byLee"))));

console.log("COMMENTS"); await seed();
const pat = () => env.authenticatedContext("leader4").firestore();
const comment = (db, uid, name, body = "Hello", metaOver = null) => { const b = writeBatch(db); b.set(doc(collection(db, "leaderAnnouncements/byLee/comments")), { body, createdBy: uid, createdByName: name, createdAt: serverTimestamp() }); b.update(doc(db, "leaderAnnouncements/byLee"), metaOver || { commentCount: increment(1), lastCommentAt: serverTimestamp(), lastCommentBy: uid, lastCommentByName: name }); return b.commit(); };
await t("leader can read comments", assertSucceeds(getDocs(collection(kim(), "leaderAnnouncements/byLee/comments"))));
await t("public cannot read comments", assertFails(getDocs(collection(pub(), "leaderAnnouncements/byLee/comments"))));
await t("listener cannot read comments", assertFails(getDocs(collection(listener(), "leaderAnnouncements/byLee/comments"))));
await t("leader can comment on someone else's announcement", assertSucceeds(comment(kim(), "leader3", "Kim")));
await t("cannot comment as someone else", assertFails(comment(kim(), "leader2", "Lee")));
await t("cannot post an empty comment", assertFails(comment(kim(), "leader3", "Kim", "")));
await t("cannot change the title while commenting", assertFails(comment(kim(), "leader3", "Kim", "Hi", { commentCount: increment(1), title: "Hacked" })));
await t("listener cannot comment", assertFails(comment(listener(), "listener1", "L")));
await t("cannot edit a comment", assertFails(updateDoc(doc(kim(), "leaderAnnouncements/byLee/comments/kimsComment"), { body: "Changed" })));
await t("uninvolved leader cannot delete a comment", assertFails(deleteDoc(doc(pat(), "leaderAnnouncements/byLee/comments/kimsComment"))));
await t("comment author can delete their own", assertSucceeds(deleteDoc(doc(kim(), "leaderAnnouncements/byLee/comments/kimsComment"))));
await t("announcement author can delete a comment on it", assertSucceeds(deleteDoc(doc(lee(), "leaderAnnouncements/byLee/comments/adminsComment"))));
await t("author can still edit with an attachment", assertSucceeds(updateDoc(doc(lee(), "leaderAnnouncements/byLee"), { title: "T2", attachment: { type: "link", url: "https://example.com", label: "x" }, edited: true })));
await t("other leader cannot add an attachment", assertFails(updateDoc(doc(kim(), "leaderAnnouncements/byLee"), { attachment: { type: "link", url: "https://evil.example", label: "x" } })));

console.log("EDITING MANAGER DETAILS"); await seed();
await t("a manager can change their own name and phone", assertSucceeds(updateDoc(doc(kim(), "leaders/leader3"), { name: "Kim Lee", phone: "555-0100", updatedAt: serverTimestamp() })));
await t("a manager cannot change their own role", assertFails(updateDoc(doc(kim(), "leaders/leader3"), { name: "Kim", role: "main_admin" })));
await t("a manager cannot change their own email", assertFails(updateDoc(doc(kim(), "leaders/leader3"), { email: "other@x.com" })));
await t("a manager cannot blank their name", assertFails(updateDoc(doc(kim(), "leaders/leader3"), { name: "" })));
await t("a manager cannot edit another manager", assertFails(updateDoc(doc(kim(), "leaders/leader2"), { name: "Hacked" })));
await t("a listener cannot edit a manager", assertFails(updateDoc(doc(listener(), "leaders/leader2"), { name: "Hacked" })));
await t("main admin can edit another manager's details and role", assertSucceeds(updateDoc(doc(admin(), "leaders/leader2"), { name: "Lee R.", phone: "555-0101", role: "main_admin" })));
await t("audio-app main admin can create their own manager record", assertSucceeds(setDoc(doc(admin(), "leaders/admin1"), { name: "Admin", phone: "", email: "a@x.com", role: "main_admin" })));
await t("a listener cannot create a manager record for themselves", assertFails(setDoc(doc(listener(), "leaders/listener1"), { name: "L", phone: "", email: "l@x.com", role: "main_admin" })));

console.log("REMOVING MANAGERS"); await seed();
await t("a manager cannot remove another manager", assertFails(deleteDoc(doc(kim(), "leaders/leader2"))));
await t("a manager cannot remove themselves from the list", assertFails(deleteDoc(doc(kim(), "leaders/leader3"))));
await t("a manager cannot promote themselves", assertFails(updateDoc(doc(kim(), "leaders/leader3"), { role: "main_admin" })));
await t("before removal, the manager can read people", assertSucceeds(getDocs(collection(lee(), "leaderPeople"))));
await t("main admin can remove a manager", assertSucceeds(deleteDoc(doc(admin(), "leaders/leader2"))));
await t("after removal, they can no longer read people", assertFails(getDocs(collection(lee(), "leaderPeople"))));
await t("after removal, they can no longer read announcements", assertFails(getDocs(collection(lee(), "leaderAnnouncements"))));
await t("after removal, they cannot re-add themselves", assertFails(setDoc(doc(lee(), "leaders/leader2"), { name: "Lee", email: "lee@x.com", role: "leader" })));

console.log("SAVED RESOURCES"); await seed();
await env.withSecurityRulesDisabled(async (ctx) => {
  const db = ctx.firestore();
  const base = { type: "note", title: "T", pinned: false };
  await setDoc(doc(db, "leaderSaved/leePersonal"), { ...base, visibility: "personal", createdBy: "leader2" });
  await setDoc(doc(db, "leaderSaved/leeShared"), { ...base, visibility: "leaders", createdBy: "leader2" });
  await setDoc(doc(db, "leaderSaved/adminOnly"), { ...base, visibility: "admins", createdBy: "admin1" });
  await setDoc(doc(db, "leaderSaved/adminPersonal"), { ...base, visibility: "personal", createdBy: "admin1" });
  await setDoc(doc(db, "leaderSaved/leeFile"), { ...base, type: "document", visibility: "leaders", createdBy: "leader2" });
});
const saved = (db) => collection(db, "leaderSaved");
const newSaved = (uid, over = {}) => ({ type: "link", title: "X", url: "https://example.com", visibility: "leaders", pinned: false, createdBy: uid, ...over });
await t("owner can read their personal resource", assertSucceeds(getDoc(doc(lee(), "leaderSaved/leePersonal"))));
await t("another leader cannot read a personal resource", assertFails(getDoc(doc(kim(), "leaderSaved/leePersonal"))));
await t("main admin cannot read someone's personal resource", assertFails(getDoc(doc(admin(), "leaderSaved/leePersonal"))));
await t("any leader can read a shared resource", assertSucceeds(getDoc(doc(kim(), "leaderSaved/leeShared"))));
await t("a leader cannot read an admins-only resource", assertFails(getDoc(doc(kim(), "leaderSaved/adminOnly"))));
await t("main admin can read an admins-only resource", assertSucceeds(getDoc(doc(admin(), "leaderSaved/adminOnly"))));
await t("public cannot read a shared resource", assertFails(getDoc(doc(pub(), "leaderSaved/leeShared"))));
await t("audio-app listener cannot read a shared resource", assertFails(getDoc(doc(listener(), "leaderSaved/leeShared"))));
await t("query: my own resources", assertSucceeds(getDocs(query(saved(lee()), where("createdBy", "==", "leader2")))));
await t("query: shared with leaders", assertSucceeds(getDocs(query(saved(kim()), where("visibility", "==", "leaders")))));
await t("query: admins-only, as main admin", assertSucceeds(getDocs(query(saved(admin()), where("visibility", "==", "admins")))));
await t("query: admins-only, as a leader is refused", assertFails(getDocs(query(saved(kim()), where("visibility", "==", "admins")))));
await t("query: someone else's resources is refused", assertFails(getDocs(query(saved(kim()), where("createdBy", "==", "leader2")))));
await t("query: everything is refused", assertFails(getDocs(saved(admin()))));
await t("query: personal ones is refused", assertFails(getDocs(query(saved(admin()), where("visibility", "==", "personal")))));
await t("leader can save a resource", assertSucceeds(addDoc(saved(kim()), newSaved("leader3"))));
await t("cannot save as someone else", assertFails(addDoc(saved(kim()), newSaved("leader2"))));
await t("leader cannot create an admins-only resource", assertFails(addDoc(saved(kim()), newSaved("leader3", { visibility: "admins" }))));
await t("leader cannot create a pinned resource", assertFails(addDoc(saved(kim()), newSaved("leader3", { pinned: true }))));
await t("main admin can create a pinned shared resource", assertSucceeds(addDoc(saved(admin()), newSaved("admin1", { pinned: true }))));
await t("a personal resource cannot be pinned", assertFails(addDoc(saved(admin()), newSaved("admin1", { pinned: true, visibility: "personal" }))));
await t("owner can edit their resource", assertSucceeds(updateDoc(doc(lee(), "leaderSaved/leeShared"), { title: "New" })));
await t("another leader cannot edit it", assertFails(updateDoc(doc(kim(), "leaderSaved/leeShared"), { title: "Hacked" })));
await t("owner cannot pin it", assertFails(updateDoc(doc(lee(), "leaderSaved/leeShared"), { pinned: true })));
await t("main admin can pin a shared resource", assertSucceeds(updateDoc(doc(admin(), "leaderSaved/leeShared"), { pinned: true })));
await t("owner can edit a pinned resource without unpinning", assertSucceeds(updateDoc(doc(lee(), "leaderSaved/leeShared"), { title: "Newer" })));
await t("owner can make it personal (which unpins it)", assertSucceeds(updateDoc(doc(lee(), "leaderSaved/leeShared"), { visibility: "personal", pinned: false })));
await t("owner cannot reassign ownership", assertFails(updateDoc(doc(lee(), "leaderSaved/leePersonal"), { createdBy: "leader3" })));
await t("another leader cannot delete it", assertFails(deleteDoc(doc(kim(), "leaderSaved/leeFile"))));
await t("main admin cannot delete a personal resource", assertFails(deleteDoc(doc(admin(), "leaderSaved/leePersonal"))));
await t("main admin can delete a shared resource", assertSucceeds(deleteDoc(doc(admin(), "leaderSaved/leeFile"))));
await t("leader can write their own favorites", assertSucceeds(setDoc(doc(kim(), "leaderSavedUsers/leader3"), { favorites: ["a"] })));
await t("leader cannot read another's favorites", assertFails(getDoc(doc(kim(), "leaderSavedUsers/leader2"))));
await t("leader cannot write another's favorites", assertFails(setDoc(doc(kim(), "leaderSavedUsers/leader2"), { favorites: [] })));

console.log("SAVED FILES (Storage)"); await seed();
await env.withSecurityRulesDisabled(async (ctx) => {
  const db = ctx.firestore();
  const base = { type: "document", title: "T", pinned: false };
  await setDoc(doc(db, "leaderSaved/leePersonal"), { ...base, visibility: "personal", createdBy: "leader2" });
  await setDoc(doc(db, "leaderSaved/leeShared"), { ...base, visibility: "leaders", createdBy: "leader2" });
  await setDoc(doc(db, "leaderSaved/adminOnly"), { ...base, visibility: "admins", createdBy: "admin1" });
  await uploadString(ref(ctx.storage(), "leaderSaved/leePersonal/a.pdf"), "x", "raw", { contentType: "application/pdf" });
  await uploadString(ref(ctx.storage(), "leaderSaved/leeShared/a.pdf"), "x", "raw", { contentType: "application/pdf" });
  await uploadString(ref(ctx.storage(), "leaderSaved/adminOnly/a.pdf"), "x", "raw", { contentType: "application/pdf" });
});
const st = (who) => (who ? env.authenticatedContext(who) : env.unauthenticatedContext()).storage();
const put = (who, path, type = "application/pdf") => uploadString(ref(st(who), path), "hello", "raw", { contentType: type });
await t("owner can open their personal file", assertSucceeds(getBytes(ref(st("leader2"), "leaderSaved/leePersonal/a.pdf"))));
await t("another leader cannot open a personal file", assertFails(getBytes(ref(st("leader3"), "leaderSaved/leePersonal/a.pdf"))));
await t("main admin cannot open someone's personal file", assertFails(getBytes(ref(st("admin1"), "leaderSaved/leePersonal/a.pdf"))));
await t("any leader can open a shared file", assertSucceeds(getBytes(ref(st("leader3"), "leaderSaved/leeShared/a.pdf"))));
await t("a leader cannot open an admins-only file", assertFails(getBytes(ref(st("leader3"), "leaderSaved/adminOnly/a.pdf"))));
await t("main admin can open an admins-only file", assertSucceeds(getBytes(ref(st("admin1"), "leaderSaved/adminOnly/a.pdf"))));
await env.withSecurityRulesDisabled(async (ctx) => { await setDoc(doc(ctx.firestore(), "leaders/invitedAdmin"), { name: "Ivy", email: "ivy@x.com", role: "main_admin" }); });
await t("invited main admin (no audio-app record) can open an admins-only file", assertSucceeds(getBytes(ref(st("invitedAdmin"), "leaderSaved/adminOnly/a.pdf"))));
await t("invited main admin can read an admins-only resource", assertSucceeds(getDoc(doc(env.authenticatedContext("invitedAdmin").firestore(), "leaderSaved/adminOnly"))));
await t("public cannot open a shared file", assertFails(getBytes(ref(st(null), "leaderSaved/leeShared/a.pdf"))));
await t("audio-app listener cannot open a shared file", assertFails(getBytes(ref(st("listener1"), "leaderSaved/leeShared/a.pdf"))));
await t("owner can upload to their resource", assertSucceeds(put("leader2", "leaderSaved/leeShared/new.pdf")));
await t("another leader cannot upload to it", assertFails(put("leader3", "leaderSaved/leeShared/evil.pdf")));
await t("cannot upload without a resource record", assertFails(put("leader3", "leaderSaved/nothingHere/a.pdf")));
await t("cannot upload a program", assertFails(put("leader2", "leaderSaved/leeShared/virus.exe", "application/octet-stream")));
await t("cannot upload a web page", assertFails(put("leader2", "leaderSaved/leeShared/page.HTML", "text/plain")));
await t("cannot upload a file typed as a web page", assertFails(put("leader2", "leaderSaved/leeShared/page.txt", "text/html")));
await t("public cannot upload", assertFails(put(null, "leaderSaved/leeShared/a2.pdf")));
await t("another leader cannot delete the file", assertFails(deleteObject(ref(st("leader3"), "leaderSaved/leeShared/a.pdf"))));
await t("main admin cannot delete a personal file", assertFails(deleteObject(ref(st("admin1"), "leaderSaved/leePersonal/a.pdf"))));
await t("owner can delete their file", assertSucceeds(deleteObject(ref(st("leader2"), "leaderSaved/leeShared/a.pdf"))));
await t("nobody can write outside the Saved folder", assertFails(put("admin1", "somewhere/else.pdf")));

console.log(`\n${pass} passed, ${fail} failed`);
await env.cleanup();
process.exit(fail ? 1 : 0);
